parameters:
  Name : 'DacPac'
  dacpacProject: ''
  nugetConfigPath : 'application/NuGet.Config'
  artifactName: ''
  project: ''

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: MSBuild@1
        inputs:
          configuration: Release
          solution: ${{ parameters.dacpacProject }}
          msbuildArguments:  /p:OutputPath=$(Build.ArtifactStagingDirectory)/${{ parameters.Name }}
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish : '$(Build.ArtifactStagingDirectory)'
          artifactName: artifacts
      - task: UniversalPackages@0
        displayName: Universal Publish
        inputs:
          command: publish
          verbosity: 'debug'
          feedsToUse: 'internal'
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          vstsFeedPublish: 'ius.taxrate.service/ius.database.artifact'
          #vstsFeedPackagePublish: '${{ parameters.project }}.artifact'
          versionOption: custom
          versionPublish: '2.1.2'
          packagePublishDescription: '<Package description>'
