parameters:
  Name : 'DacPac'
  dacpacProject: ''
  nugetConfigPath : 'application/NuGet.Config'
  artifactName: ''

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: MSBuild@1
        inputs:
          configuration: Release
          solution: ${{ parameters.dacpacProject }}
          msbuildArguments:  /p:OutputPath=$(Build.ArtifactStagingDirectory)/${{ parameters.Name }}
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish : '$(Build.ArtifactStagingDirectory)'
          artifactName: artifacts
      - task: UniversalPackages@0
        displayName: Universal Publish
        inputs:
          command: 'publish'
          publishDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.Name }}'
          vstsFeedPublish: 'ius.database.artifact'
          vstsFeedPackagePublish: '${{ parameters.artifactName }}'
          versionOption: 'minor'
          packagePublishDescription: 'database dacpac artifact'
          verbosity: 'debug'
