parameters:
  autorestClientFeed: ''
  autorestProjectName: ''
  version: ''
  semVersion: ''
  containerServiceEndpoint: ''
  registry: ''
  project: ''
  helmChartLocation: ''
  helmChartName : ''
  latestName: ''
  imageName: ''
  dockerRunOptions: ''
  autorestTag: 'latest'
  autorestImageName: 'autorest-auto-generator'
  autorestAzureContainerRegistryName: 'iusdev'
  restClientGenerator: 'rest-client-generator'

steps:
  - ${{ if and(eq(parameters.autorestProjectName, 'Tax'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), and(eq(variables['UsingDevelopBranch'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))) }}:
    - task: AzureCLI@1
      displayName: Building New Generation Client
      condition: succeeded()
      inputs:
        azureSubscription : ${{ parameters.containerServiceEndpoint }}
        scriptLocation: inlineScript
        inlineScript: |
          echo 'Creating Appsettings folder at $(Build.ArtifactStagingDirectory)'
          mkdir $(Build.ArtifactStagingDirectory)/appsettings
          echo '{
            "ClientStateID" : 0,
            "AppSettings" : {
               "URLs" : {
                 "IdentityServer" : "https://iusbuildidentityserver.azurewebsites.net"
               }
            },
            "Data": {
              "Queue": {
                "GlobalDisable": true
              },
              "Identity": {
                 "ApiScope": "api1"
               }
            },
            "Serilog":{
              "MinimumLevel": "Information",
               "Using": [
                   "Serilog.Sinks.Console"
               ],
               "WriteTo": [
                   {
                       "Name": "Console"
                   }
               ]
            },
            "UseIncludedCertificate" : "true",
            "DoNotFetchDiscovery" : "true",
            "DoNotRequireHttps" : "true",
            "BuildServer" : "true",
            "ConfigurationDump" : "true"
           }' > $(Build.ArtifactStagingDirectory)/appsettings/appsettings.Consortium.Production.json
           docker network create crossChatter
           docker run -d --name swagger-converter --net crossChatter iusdev.azurecr.io/swagger-converter
           docker run -d -e "APPSETTING_LOCATION=/data/appsettings" --name ${{ parameters.autorestProjectName }} -v $(Build.ArtifactStagingDirectory)/appsettings:/data/appsettings --net=crossChatter ${{ parameters.imageName }}
           docker run --net=crossChatter ${{ parameters.registry }}/${{ parameters.restClientGenerator }}:latest dotnet iUS.RestClientGenerator.dll --project ${{ parameters.autorestProjectName }} --domain ${{ parameters.autorestClientFeed }} --template ${{ parameters.autorestTemplateType }} --version ${{ parameters.version }} --dockerService http://${{ parameters.autorestProjectName }} --dockerSwaggerToAPI http://swagger-converter:8080/api/convert

  - ${{ if ne(parameters.autorestProjectName, '') }}:
    - task: AzureCLI@1
      displayName: Building Autorest Client
      condition: succeeded()
      inputs:
        azureSubscription : ${{ parameters.containerServiceEndpoint }}
        scriptLocation: inlineScript
        inlineScript: |
          mkdir $(Build.ArtifactStagingDirectory)/autorest
          docker run --cpus 0 --net=host --mount type=bind,src=$(Build.ArtifactStagingDirectory)/autorest,dst=/autorest/dist ${{ parameters.autorestAzureContainerRegistryName }}.azurecr.io/${{ parameters.autorestImageName }}:${{ parameters.autorestTag }} python3 main.py --projectName ${{ parameters.autorestProjectName }}
          ls -al $(Build.ArtifactStagingDirectory)/autorest
    - task: NuGetCommand@2
      displayName: 'Autorest client NuGet push'
      condition:
        and
        (
          succeeded(),
          or
          (
            eq(variables['Build.SourceBranch'], 'refs/heads/master'),
            and
            (
              eq(variables['UsingDevelopBranch'], 'true'),
              eq(variables['Build.SourceBranch'], 'refs/heads/devlop')
            )
          )
        )
      inputs:
        command: push
        publishVstsFeed: '${{ parameters.autorestClientFeed }}'
        allowPackageConflicts: false
        packagesToPush: '$(Build.ArtifactStagingDirectory)/autorest/*.nupkg'
