parameters:
  autorestClientFeed: ''
  autorestProjectName: ''
  autorestTemplateType: 'Service'
  version: ''
  semVersion: ''
  containerServiceEndpoint: ''
  registry: ''
  project: ''
  helmChartLocation: ''
  helmChartName : ''
  latestName: ''
  imageName: ''
  stateCode: 0

steps:
  - template: ../helm/helm-chart-pipeline-template.yaml
    parameters:
      project: '${{ parameters.project }}'
      version: '${{ parameters.version }}'
      semVersion: '${{ parameters.semVersion }}'
      containerServiceEndpoint: '${{ parameters.containerServiceEndpoint }}'
      helmChartLocation: '${{ parameters.helmChartLocation }}'
      helmChartName : '${{ parameters.helmChartName }}'
