parameters:
  autorestClientFeed: ''
  autorestProjectName: ''
  autorestTemplateType: 'Service'
  version: ''
  semVersion: ''
  containerServiceEndpoint: ''
  registry: ''
  project: ''
  helmChartLocation: ''
  helmChartName : ''
  latestName: ''
  imageName: ''
  stateCode: 0

steps:
  - task: Docker@1
    displayName: Container registry login
    inputs:
      azureSubscriptionEndpoint: ${{ parameters.containerServiceEndpoint }}
      azureContainerRegistry: ${{ parameters.registry }}
      command: login
  - script: |
      if [[ -f "application/Dockerfile" ]]; then 
        echo "Using included Dockerfile.  Please consider updating to newest pattern"
      elif [[ -f "dockerfile.json" ]]; then
        echo "Generating new Dockerfile from the dockerfile.mustache"
        docker run --net=host -v $(Build.SourcesDirectory):/src ${{ parameters.registry }}/dockerfile-template:latest node /data/state_code_updater /src/dockerfile.json ${{ parameters.stateCode }}
        docker run --net=host -v $(Build.SourcesDirectory):/src ${{ parameters.registry }}/dockerfile-template:latest mustache /src/dockerfile.json /data/Dockerfile.mustache > application/Dockerfile
        cat application/Dockerfile
      else
        echo "Dockerfile is not present and neither is a required dockerfile.json"
        exit 1
      fi
    displayName: Check for Dockerfile
  - template: ../helm/helm-chart-pipeline-template.yaml
    parameters:
      project: '${{ parameters.project }}'
      version: '${{ parameters.version }}'
      semVersion: '${{ parameters.semVersion }}'
      containerServiceEndpoint: '${{ parameters.containerServiceEndpoint }}'
      helmChartLocation: '${{ parameters.helmChartLocation }}'
      helmChartName : '${{ parameters.helmChartName }}'
